package com.iot.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the traffic summary between two IPs for a specific day.
 * Generated by SummarizeWorker, consumed by ConsolidatorWorker.
 */
public record IntermediateSummary(
        @JsonProperty("src_ip") String srcIp,
        @JsonProperty("dst_ip") String dstIp,
        @JsonProperty("date") String date, // Format YYYY-MM-DD
        @JsonProperty("total_flow_duration") long totalFlowDuration,
        @JsonProperty("total_fwd_packets") long totalFwdPackets
) {}